#pragma checksum "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "1BBAF9F099D1438638CC963CFEC6B20D7C92A442"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Account_ResetPassword : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
    protected global::System.Web.UI.WebControls.ChangePassword ChangeUserPassword;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected ASP.global_asax ApplicationInstance {
        get {
            return ((ASP.global_asax)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 3 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 387 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 393 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 400 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 3 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 388 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 392 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 398 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 391 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 395 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 3 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 396 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 3 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 390 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 399 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 386 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 394 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 389 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 405 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 404 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class account_resetpassword_aspx : global::Account_ResetPassword, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.account_resetpassword_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public account_resetpassword_aspx() {
            string[] dependencies;
            
            #line 912304 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/Account/ResetPassword.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.account_resetpassword_aspx.@__initialized == false)) {
                global::ASP.account_resetpassword_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[4];
                dependencies[0] = "~/Account/ResetPassword.aspx";
                dependencies[1] = "~/Site.master";
                dependencies[2] = "~/Site.master.cs";
                dependencies[3] = "~/Account/ResetPassword.aspx.cs";
                global::ASP.account_resetpassword_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.account_resetpassword_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        235,
                        2,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.VisualStudio.Web.PageInspector.Runtime.WebForms.TraceHelpers, Microsoft" +
                    ".VisualStudio.Web.PageInspector.Runtime, Version=1.3.0.0, Culture=neutral, Publi" +
                    "cKeyToken=b03f5f7f11d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.account_resetpassword_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.account_resetpassword_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 3 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 3 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control3() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n       ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        330,
                        9,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control5() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n            <span class=\"failureNotification\">\r\n                ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        566,
                        66,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Literal @__BuildControl__control6() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            
            #line 10 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            
            #line 10 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.ID = "FailureText";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        632,
                        59,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control7() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n            </span>\r\n            ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        691,
                        35,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ValidationSummary @__BuildControl__control8() {
            global::System.Web.UI.WebControls.ValidationSummary @__ctrl;
            
            #line 12 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ValidationSummary();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 12 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.ID = "ChangeUserPasswordValidationSummary";
            
            #line default
            #line hidden
            
            #line 12 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.CssClass = "failureNotification";
            
            #line default
            #line hidden
            
            #line 12 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.ValidationGroup = "ChangeUserPasswordValidationGroup";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        726,
                        182,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control9() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n            <div class=\"accountInfo\">\r\n                <fieldset class=\"changeP" +
                    "assword\">\r\n                    <legend>Reset Password</legend>            \r\n    " +
                    "                <p>\r\n                        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        908,
                        206,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control11() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("New Password:");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1196,
                        13,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControl__control10() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 18 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 18 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.ID = "NewPasswordLabel";
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.AssociatedControlID = "NewPassword";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 18 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl1 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 18 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1114,
                        107,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control12() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1221,
                        26,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControl__control13() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 19 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 19 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.ID = "NewPassword";
            
            #line default
            #line hidden
            
            #line 19 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.CssClass = "passwordEntry";
            
            #line default
            #line hidden
            
            #line 19 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Password;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1247,
                        104,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control14() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1351,
                        26,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control16() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("*");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1699,
                        1,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControl__control15() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 20 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 20 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.ID = "NewPasswordRequired";
            
            #line default
            #line hidden
            
            #line 20 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.ControlToValidate = "NewPassword";
            
            #line default
            #line hidden
            
            #line 20 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.CssClass = "failureNotification";
            
            #line default
            #line hidden
            
            #line 20 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.ErrorMessage = "New Password is required.";
            
            #line default
            #line hidden
            
            #line 20 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.ToolTip = "New Password is required.";
            
            #line default
            #line hidden
            
            #line 20 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.ValidationGroup = "ChangeUserPasswordValidationGroup";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 20 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl1 = this.@__BuildControl__control16();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 20 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1377,
                        352,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control17() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                    </p>\r\n                    <p>\r\n                        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1729,
                        77,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control19() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("Confirm New Password:");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1902,
                        21,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControl__control18() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 25 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 25 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.ID = "ConfirmNewPasswordLabel";
            
            #line default
            #line hidden
            
            #line 25 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.AssociatedControlID = "ConfirmNewPassword";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 25 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl1 = this.@__BuildControl__control19();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 25 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1806,
                        129,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control20() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1935,
                        26,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControl__control21() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 26 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 26 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.ID = "ConfirmNewPassword";
            
            #line default
            #line hidden
            
            #line 26 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.CssClass = "passwordEntry";
            
            #line default
            #line hidden
            
            #line 26 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Password;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1961,
                        111,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control22() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2072,
                        26,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control24() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("*");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2467,
                        1,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControl__control23() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 27 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 27 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.ID = "ConfirmNewPasswordRequired";
            
            #line default
            #line hidden
            
            #line 27 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.ControlToValidate = "ConfirmNewPassword";
            
            #line default
            #line hidden
            
            #line 27 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.CssClass = "failureNotification";
            
            #line default
            #line hidden
            
            #line 27 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 27 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.ErrorMessage = "Confirm New Password is required.";
            
            #line default
            #line hidden
            
            #line 27 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.ToolTip = "Confirm New Password is required.";
            
            #line default
            #line hidden
            
            #line 27 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.ValidationGroup = "ChangeUserPasswordValidationGroup";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 27 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl1 = this.@__BuildControl__control24();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 27 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2098,
                        399,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control25() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2497,
                        26,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control27() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("*");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2891,
                        1,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CompareValidator @__BuildControl__control26() {
            global::System.Web.UI.WebControls.CompareValidator @__ctrl;
            
            #line 30 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CompareValidator();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 30 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.ID = "NewPasswordCompare";
            
            #line default
            #line hidden
            
            #line 30 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.ControlToCompare = "NewPassword";
            
            #line default
            #line hidden
            
            #line 30 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.ControlToValidate = "ConfirmNewPassword";
            
            #line default
            #line hidden
            
            #line 30 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.CssClass = "failureNotification";
            
            #line default
            #line hidden
            
            #line 30 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 30 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.ErrorMessage = "The Confirm New Password must match the New Password entry.";
            
            #line default
            #line hidden
            
            #line 30 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.ValidationGroup = "ChangeUserPasswordValidationGroup";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 30 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl1 = this.@__BuildControl__control27();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 30 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2523,
                        392,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control28() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                    </p>\r\n                </fieldset>\r\n                <p class" +
                    "=\"submitButton\"> \r\n                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2915,
                        120,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControl__control29() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 36 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 36 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.ID = "ConfirmButton";
            
            #line default
            #line hidden
            
            #line 36 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.CommandName = "Confirm";
            
            #line default
            #line hidden
            
            #line 36 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.Text = "Confirm";
            
            #line default
            #line hidden
            
            #line 36 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.ValidationGroup = "ChangeUserPasswordValidationGroup";
            
            #line default
            #line hidden
            
            #line 36 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.Click += new System.EventHandler(this.ConfrimButton_Click1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3035,
                        195,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control30() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                </p>\r\n            </div>\r\n        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3230,
                        52,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control4(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl1 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Literal @__ctrl2;
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl2 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl3 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ValidationSummary @__ctrl4;
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl4 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl5 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl6;
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl6 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl7;
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl7 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl8;
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl8 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl9;
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl9 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl10;
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl10 = this.@__BuildControl__control15();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl11;
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl11 = this.@__BuildControl__control17();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl12;
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl12 = this.@__BuildControl__control18();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl13;
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl13 = this.@__BuildControl__control20();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl13);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl14;
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl14 = this.@__BuildControl__control21();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl14);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl15;
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl15 = this.@__BuildControl__control22();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl15);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl16;
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl16 = this.@__BuildControl__control23();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl16);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl17;
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl17 = this.@__BuildControl__control25();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl17);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CompareValidator @__ctrl18;
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl18 = this.@__BuildControl__control26();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl18);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl19;
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl19 = this.@__BuildControl__control28();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl19);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl20;
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl20 = this.@__BuildControl__control29();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl20);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl21;
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl21 = this.@__BuildControl__control30();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl21);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ChangePassword @__BuildControlChangeUserPassword() {
            global::System.Web.UI.WebControls.ChangePassword @__ctrl;
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ChangePassword();
            
            #line default
            #line hidden
            this.ChangeUserPassword = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.ChangePasswordTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control4));
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.ID = "ChangeUserPassword";
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.CancelDestinationPageUrl = "~/";
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.EnableViewState = false;
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.RenderOuterTable = false;
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.SuccessPageUrl = "ChangePasswordSuccess.aspx";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        339,
                        2995,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control31() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3334,
                        2,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent2(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 5 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 5 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ChangePassword @__ctrl2;
            
            #line 5 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl2 = this.@__BuildControlChangeUserPassword();
            
            #line default
            #line hidden
            
            #line 5 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 5 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl3 = this.@__BuildControl__control31();
            
            #line default
            #line hidden
            
            #line 5 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(account_resetpassword_aspx @__ctrl) {
            
            #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.Title = "";
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__ctrl.MasterPageFile = "~/Site.master";
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            this.AddContentTemplate("HeadContent", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            
            #line 5 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            this.AddContentTemplate("MainContent", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent2)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ResetPassword.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.account_resetpassword_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.account_resetpassword_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -723095943;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
