#pragma checksum "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "51F5BD50725798F051E56ED98E3AE5F7DC98CB45"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Order_shoppingcart : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 17 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
    protected global::System.Web.UI.WebControls.DataGrid ShoppingCartDlt;
    
    #line default
    #line hidden
    
    
    #line 30 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
    protected global::System.Web.UI.WebControls.Button update;
    
    #line default
    #line hidden
    
    
    #line 31 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
    protected global::System.Web.UI.WebControls.Button CheckOut;
    
    #line default
    #line hidden
    
    
    #line 35 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
    protected global::System.Web.UI.WebControls.Label label;
    
    #line default
    #line hidden
    
    
    #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
    protected global::System.Web.UI.HtmlControls.HtmlForm Form1;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected ASP.global_asax ApplicationInstance {
        get {
            return ((ASP.global_asax)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 3 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 387 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 393 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 400 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 3 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 388 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 392 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 398 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 391 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 395 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 3 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 396 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 3 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 390 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 399 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 386 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 394 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 389 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 405 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 404 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class order_shoppingcart_aspx : global::Order_shoppingcart, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.order_shoppingcart_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static bool @__initialized;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public order_shoppingcart_aspx() {
            string[] dependencies;
            
            #line 912304 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/Order/shoppingcart.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.order_shoppingcart_aspx.@__initialized == false)) {
                dependencies = new string[4];
                dependencies[0] = "~/Order/shoppingcart.aspx";
                dependencies[1] = "~/Site.master";
                dependencies[2] = "~/Site.master.cs";
                dependencies[3] = "~/Order/shoppingcart.aspx.cs";
                global::ASP.order_shoppingcart_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.order_shoppingcart_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        231,
                        2,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.VisualStudio.Web.PageInspector.Runtime.WebForms.TraceHelpers, Microsoft" +
                    ".VisualStudio.Web.PageInspector.Runtime, Version=1.3.0.0, Culture=neutral, Publi" +
                    "cKeyToken=b03f5f7f11d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.order_shoppingcart_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.order_shoppingcart_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 3 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 3 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control3() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"

    <title>shoppingcart 
</title> 
<meta http-equiv=""Content-Type"" content=""text/html; 
charset=gb2312""> <LINK href=""mycss.css"" type=""text/css"" rel=""stylesheet""> 
<meta name=""vs_defaultClientScript"" content=""JavaScript""> 
<meta name=""vs_targetSchema"" content=""http://schemas.microsoft.com/intellisense/ie5""> </HEAD> 
<body> <center> 
");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        330,
                        345,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control4() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(" <table width=\"500\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"> <tr> <td> \r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        707,
                        76,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control8() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(" <center> \r\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1121,
                        12,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CheckBox @__BuildControl__control9() {
            global::System.Web.UI.WebControls.CheckBox @__ctrl;
            
            #line 20 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CheckBox();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 20 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.ID = "chkProductID";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1133,
                        49,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control10() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(" </center> \r\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1182,
                        13,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control7(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 18 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl1 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 18 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CheckBox @__ctrl2;
            
            #line 18 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl2 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 18 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl3 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TemplateColumn @__BuildControl__control6() {
            global::System.Web.UI.WebControls.TemplateColumn @__ctrl;
            
            #line 18 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TemplateColumn();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control7));
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.HeaderText = "Delete";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundColumn @__BuildControl__control11() {
            global::System.Web.UI.WebControls.BoundColumn @__ctrl;
            
            #line 22 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundColumn();
            
            #line default
            #line hidden
            
            #line 22 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.DataField = "ProdID";
            
            #line default
            #line hidden
            
            #line 22 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.HeaderText = "ID";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundColumn @__BuildControl__control12() {
            global::System.Web.UI.WebControls.BoundColumn @__ctrl;
            
            #line 23 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundColumn();
            
            #line default
            #line hidden
            
            #line 23 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.DataField = "ProName";
            
            #line default
            #line hidden
            
            #line 23 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.HeaderText = "Product Name";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundColumn @__BuildControl__control13() {
            global::System.Web.UI.WebControls.BoundColumn @__ctrl;
            
            #line 24 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundColumn();
            
            #line default
            #line hidden
            
            #line 24 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.DataField = "UnitPrice";
            
            #line default
            #line hidden
            
            #line 24 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.HeaderText = "Price";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control16() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(" \r\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1481,
                        3,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControl__control17() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 27 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 27 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.ID = "CountTb";
            
            #line default
            #line hidden
            
            #line 27 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control17);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1484,
                        118,
                        false});
            return @__ctrl;
        }
        
        public void @__DataBinding__control17(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.TextBox dataBindingExpressionBuilderTarget;
            System.Web.UI.WebControls.DataGridItem Container;
            
            #line 27 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.TextBox)(sender));
            
            #line default
            #line hidden
            
            #line 27 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            Container = ((System.Web.UI.WebControls.DataGridItem)(dataBindingExpressionBuilderTarget.BindingContainer));
            
            #line default
            #line hidden
            
            #line 27 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            dataBindingExpressionBuilderTarget.Text = global::System.Convert.ToString(DataBinder.Eval( Container.DataItem,"ProdCount" ), global::System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control18() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(" \r\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1602,
                        3,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control15(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 25 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl1 = this.@__BuildControl__control16();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 25 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl2;
            
            #line 25 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl2 = this.@__BuildControl__control17();
            
            #line default
            #line hidden
            
            #line 25 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 25 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl3 = this.@__BuildControl__control18();
            
            #line default
            #line hidden
            
            #line 25 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TemplateColumn @__BuildControl__control14() {
            global::System.Web.UI.WebControls.TemplateColumn @__ctrl;
            
            #line 25 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TemplateColumn();
            
            #line default
            #line hidden
            
            #line 25 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control15));
            
            #line default
            #line hidden
            
            #line 25 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.HeaderText = "Quatity";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundColumn @__BuildControl__control19() {
            global::System.Web.UI.WebControls.BoundColumn @__ctrl;
            
            #line 29 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundColumn();
            
            #line default
            #line hidden
            
            #line 29 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.DataField = "TotalPrice";
            
            #line default
            #line hidden
            
            #line 29 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.HeaderText = "Price";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control5(System.Web.UI.WebControls.DataGridColumnCollection @__ctrl) {
            global::System.Web.UI.WebControls.TemplateColumn @__ctrl1;
            
            #line 17 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl1 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 17 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundColumn @__ctrl2;
            
            #line 17 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl2 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 17 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundColumn @__ctrl3;
            
            #line 17 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl3 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 17 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundColumn @__ctrl4;
            
            #line 17 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl4 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 17 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.Add(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TemplateColumn @__ctrl5;
            
            #line 17 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl5 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            
            #line 17 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.Add(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundColumn @__ctrl6;
            
            #line 17 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl6 = this.@__BuildControl__control19();
            
            #line default
            #line hidden
            
            #line 17 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.Add(@__ctrl6);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.DataGrid @__BuildControlShoppingCartDlt() {
            global::System.Web.UI.WebControls.DataGrid @__ctrl;
            
            #line 17 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.DataGrid();
            
            #line default
            #line hidden
            this.ShoppingCartDlt = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 17 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.ID = "ShoppingCartDlt";
            
            #line default
            #line hidden
            
            #line 17 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(500D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 17 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.BackColor = global::System.Drawing.Color.White;
            
            #line default
            #line hidden
            
            #line 17 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.BorderColor = global::System.Drawing.Color.Black;
            
            #line default
            #line hidden
            
            #line 17 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.ShowFooter = false;
            
            #line default
            #line hidden
            
            #line 17 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.CellPadding = 3;
            
            #line default
            #line hidden
            
            #line 17 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.CellSpacing = 0;
            
            #line default
            #line hidden
            
            #line 17 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.Font.Name = "Verdana";
            
            #line default
            #line hidden
            
            #line 17 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.Font.Size = new System.Web.UI.WebControls.FontUnit(new System.Web.UI.WebControls.Unit(8D, global::System.Web.UI.WebControls.UnitType.Point));
            
            #line default
            #line hidden
            
            #line 17 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.HeaderStyle.BackColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(206, 207, 214)));
            
            #line default
            #line hidden
            
            #line 17 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.AutoGenerateColumns = false;
            
            #line default
            #line hidden
            
            #line 17 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("MaintainState", "true");
            
            #line default
            #line hidden
            
            #line 17 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            this.@__BuildControl__control5(@__ctrl.Columns);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        783,
                        950,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control20() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("</td> </tr> </table> <br> <table width=\"500\" border=\"0\" cellspacing=\"0\" cellpaddi" +
                    "ng=\"0\"> <tr> <td> \r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1733,
                        101,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlupdate() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 30 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.update = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 30 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.ID = "update";
            
            #line default
            #line hidden
            
            #line 30 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.Text = "Update My Shopping Cart";
            
            #line default
            #line hidden
            
            #line 30 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.CssClass = "button2";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1834,
                        91,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control21() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("</td> <td> \r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1925,
                        13,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlCheckOut() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 31 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.CheckOut = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 31 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.ID = "CheckOut";
            
            #line default
            #line hidden
            
            #line 31 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.Text = "Check Out";
            
            #line default
            #line hidden
            
            #line 31 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.CssClass = "button5";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1938,
                        79,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control22() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(" \r\n<input type=\"button\" name=\"close2\" value=\"Continue My Shopping\" onClick=\"windo" +
                    "w.close( ); \r\nreturn false; \r\n\" class=\"button2\"></td> <td align=\"right\"><br> \r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2017,
                        160,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControllabel() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 35 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.label = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 35 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.ID = "label";
            
            #line default
            #line hidden
            
            #line 35 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 35 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.Visible = true;
            
            #line default
            #line hidden
            
            #line 35 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.ForeColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(255, 128, 128)));
            
            #line default
            #line hidden
            
            #line 35 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.Height = new System.Web.UI.WebControls.Unit(18D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2177,
                        112,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control23() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("</td> </tr> </table> \r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2289,
                        23,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlForm1() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.Form1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.ID = "Form1";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl1 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.DataGrid @__ctrl2;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl2 = this.@__BuildControlShoppingCartDlt();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl3 = this.@__BuildControl__control20();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl4;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl4 = this.@__BuildControlupdate();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl5 = this.@__BuildControl__control21();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl6;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl6 = this.@__BuildControlCheckOut();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl7;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl7 = this.@__BuildControl__control22();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl8;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl8 = this.@__BuildControllabel();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl9;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl9 = this.@__BuildControl__control23();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        675,
                        1644,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control24() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(" </center> \r\n</body>\r\n\r\n\r\n\r\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2319,
                        28,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent2(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 7 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 7 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl2;
            
            #line 7 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl2 = this.@__BuildControlForm1();
            
            #line default
            #line hidden
            
            #line 7 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 7 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl3 = this.@__BuildControl__control24();
            
            #line default
            #line hidden
            
            #line 7 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(order_shoppingcart_aspx @__ctrl) {
            
            #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.Title = "";
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__ctrl.MasterPageFile = "~/Site.master";
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            this.AddContentTemplate("HeadContent", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            
            #line 7 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            this.AddContentTemplate("MainContent", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent2)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Order\shoppingcart.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.order_shoppingcart_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 1647016089;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
