//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.18446")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.0")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_pb2b4nkl {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_pb2b4nkl() {
        }
        
        static object Create_ASP_products_wheels_aspx() {
            return new ASP.products_wheels_aspx();
        }
        
        static object Create_ASP_products_tire_aspx() {
            return new ASP.products_tire_aspx();
        }
        
        static object Create_ASP_products_wheelall_aspx() {
            return new ASP.products_wheelall_aspx();
        }
        
        static object Create_ASP_products_viewbyvehicle_aspx() {
            return new ASP.products_viewbyvehicle_aspx();
        }
        
        static object Create_ASP_products_productsite_master() {
            return new ASP.products_productsite_master();
        }
        
        static object Create_ASP_products_tireall_aspx() {
            return new ASP.products_tireall_aspx();
        }
        
        static object Create_ASP_products_accessories_aspx() {
            return new ASP.products_accessories_aspx();
        }
        
        static object Create_ASP_products_tirebyvehicle_aspx() {
            return new ASP.products_tirebyvehicle_aspx();
        }
        
        static object Create_ASP_products_accall_aspx() {
            return new ASP.products_accall_aspx();
        }
    }
}
