#pragma checksum "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "F43E47C306F9514C9113DF044772F314702202F7"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Default2 : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 31 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
    protected global::System.Web.UI.WebControls.PasswordRecovery PasswordRecovery1;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected ASP.global_asax ApplicationInstance {
        get {
            return ((ASP.global_asax)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 3 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 387 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 393 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 400 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 3 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 388 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 392 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 398 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 391 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 395 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 3 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 396 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 3 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 390 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 399 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 386 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 394 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 389 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 405 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 404 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class account_forgetpassword_aspx : global::Default2, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.account_forgetpassword_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static bool @__initialized;
        
        private static object @__fileDependencies;
        
        
        #line 8 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
                           

        // Set the field label background color if the user name is not found.
        void PasswordRecovery1_UserLookupError(object sender, System.EventArgs e)
        {
            PasswordRecovery1.LabelStyle.ForeColor = System.Drawing.Color.Red;
        }

        // Reset the field label background color.
        void PasswordRecovery1_Load(object sender, System.EventArgs e)
        {
            PasswordRecovery1.LabelStyle.ForeColor = System.Drawing.Color.Black;
        }
        
        void PasswordRecovery1_SendingMail(object sender, MailMessageEventArgs e)
        {
            e.Message.IsBodyHtml = false;
            e.Message.Subject = "New password on Web site.";
        }
    
        #line default
        #line hidden
        
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public account_forgetpassword_aspx() {
            string[] dependencies;
            
            #line 912304 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/Account/ForgetPassword.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.account_forgetpassword_aspx.@__initialized == false)) {
                dependencies = new string[4];
                dependencies[0] = "~/Account/ForgetPassword.aspx";
                dependencies[1] = "~/Site.master";
                dependencies[2] = "~/Site.master.cs";
                dependencies[3] = "~/Account/ForgetPassword.aspx.cs";
                global::ASP.account_forgetpassword_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.account_forgetpassword_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        223,
                        2,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.VisualStudio.Web.PageInspector.Runtime.WebForms.TraceHelpers, Microsoft" +
                    ".VisualStudio.Web.PageInspector.Runtime, Version=1.3.0.0, Culture=neutral, Publi" +
                    "cKeyToken=b03f5f7f11d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.account_forgetpassword_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.account_forgetpassword_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 3 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 3 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control3() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    <!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www." +
                    "w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n\r\n    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        318,
                        135,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control5() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n            <table border=\"0\" style=\"font-size: 10pt;\">\r\n                <tr>\r\n" +
                    "                    <td>Your password has been sent to you.</td>\r\n              " +
                    "  </tr>\r\n            </table>\r\n        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1735,
                        200,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control4(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 31 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__ctrl1 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 31 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control6(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            
            #line 31 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__ctrl.Font.Bold = true;
            
            #line default
            #line hidden
            
            #line 31 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.White;
            
            #line default
            #line hidden
            
            #line 31 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__ctrl.BackColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(107, 105, 107)));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.PasswordRecovery @__BuildControlPasswordRecovery1() {
            global::System.Web.UI.WebControls.PasswordRecovery @__ctrl;
            
            #line 31 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.PasswordRecovery();
            
            #line default
            #line hidden
            this.PasswordRecovery1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 31 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__ctrl.SuccessTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control4));
            
            #line default
            #line hidden
            
            #line 31 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__ctrl.ID = "PasswordRecovery1";
            
            #line default
            #line hidden
            
            #line 31 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__ctrl.BorderStyle = global::System.Web.UI.WebControls.BorderStyle.Solid;
            
            #line default
            #line hidden
            
            #line 31 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__ctrl.BorderWidth = new System.Web.UI.WebControls.Unit(1D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 31 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__ctrl.BackColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(247, 247, 222)));
            
            #line default
            #line hidden
            
            #line 31 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__ctrl.Font.Size = new System.Web.UI.WebControls.FontUnit(new System.Web.UI.WebControls.Unit(10D, global::System.Web.UI.WebControls.UnitType.Point));
            
            #line default
            #line hidden
            
            #line 31 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__ctrl.Font.Names = new string[] {
                    "Verdana"};
            
            #line default
            #line hidden
            
            #line 31 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__ctrl.BorderColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(204, 204, 153)));
            
            #line default
            #line hidden
            
            #line 31 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__ctrl.HelpPageText = "Need help?";
            
            #line default
            #line hidden
            
            #line 31 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__ctrl.HelpPageUrl = "recoveryHelp.aspx";
            
            #line default
            #line hidden
            
            #line 31 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__ctrl.MailDefinition.From = "neo.wu2@gmail.com";
            
            #line default
            #line hidden
            
            #line 31 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            this.@__BuildControl__control6(@__ctrl.TitleTextStyle);
            
            #line default
            #line hidden
            
            #line 31 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__ctrl.UserLookupError += new System.EventHandler(this.PasswordRecovery1_UserLookupError);
            
            #line default
            #line hidden
            
            #line 31 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__ctrl.Load += new System.EventHandler(this.PasswordRecovery1_Load);
            
            #line default
            #line hidden
            
            #line 31 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__ctrl.SendingMail += new System.Web.UI.WebControls.MailMessageEventHandler(this.PasswordRecovery1_SendingMail);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1272,
                        811,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control7() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2083,
                        4,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent2(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 5 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 5 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.PasswordRecovery @__ctrl2;
            
            #line 5 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__ctrl2 = this.@__BuildControlPasswordRecovery1();
            
            #line default
            #line hidden
            
            #line 5 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 5 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__ctrl3 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 5 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(account_forgetpassword_aspx @__ctrl) {
            
            #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__ctrl.Title = "";
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__ctrl.MasterPageFile = "~/Site.master";
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 3 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            this.AddContentTemplate("HeadContent", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            
            #line 5 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            this.AddContentTemplate("MainContent", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent2)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ForgetPassword.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.account_forgetpassword_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 1760824524;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
