#pragma checksum "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "D22AD7AE2DD40DDE9708F52EFDC3AFAB23D8D5FB"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class SiteMaster {
    
    
    #line 8 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
    protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;
    
    #line default
    #line hidden
    
    
    #line 21 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
    protected global::System.Web.UI.WebControls.LoginView HeadLoginView;
    
    #line default
    #line hidden
    
    
    #line 32 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
    protected global::System.Web.UI.WebControls.Menu NavigationMenu;
    
    #line default
    #line hidden
    
    
    #line 48 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
    protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected ASP.global_asax ApplicationInstance {
        get {
            return ((ASP.global_asax)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 392 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 399 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 390 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 388 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 394 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 8 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 405 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 8 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 404 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    #line 395 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 391 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 386 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 393 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 400 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 396 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 387 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 8 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 8 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 389 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 398 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 8 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class products_productsite_master : global::SiteMaster {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.products_productsite_master.@__PageInspector_LoadHelper("SetTraceData");
        
        private System.Web.UI.ITemplate @__Template_HeadContent;
        
        private System.Web.UI.ITemplate @__Template_MainContent;
        
        private static bool @__initialized;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public products_productsite_master() {
            
            #line 912304 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master.cs"
            ((global::System.Web.UI.MasterPage)(this)).AppRelativeVirtualPath = "~/Products/ProductSite.master";
            
            #line default
            #line hidden
            if ((global::ASP.products_productsite_master.@__initialized == false)) {
                global::ASP.products_productsite_master.@__initialized = true;
            }
            this.ContentPlaceHolders.Add("headcontent");
            this.ContentPlaceHolders.Add("maincontent");
        }
        
        [TemplateContainer(typeof(System.Web.UI.MasterPage))]
        [TemplateInstanceAttribute(System.Web.UI.TemplateInstance.Single)]
        public virtual System.Web.UI.ITemplate Template_HeadContent {
            get {
                return this.@__Template_HeadContent;
            }
            set {
                this.@__Template_HeadContent = value;
            }
        }
        
        [TemplateContainer(typeof(System.Web.UI.MasterPage))]
        [TemplateInstanceAttribute(System.Web.UI.TemplateInstance.Single)]
        public virtual System.Web.UI.ITemplate Template_MainContent {
            get {
                return this.@__Template_MainContent;
            }
            set {
                this.@__Template_MainContent = value;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/" +
                    "xhtml1/DTD/xhtml1-strict.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:la" +
                    "ng=\"en\">\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        105,
                        170,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.VisualStudio.Web.PageInspector.Runtime.WebForms.TraceHelpers, Microsoft" +
                    ".VisualStudio.Web.PageInspector.Runtime, Version=1.3.0.0, Culture=neutral, Publi" +
                    "cKeyToken=b03f5f7f11d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.products_productsite_master.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.products_productsite_master.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTitle @__BuildControl__control4() {
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl;
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTitle();
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        301,
                        15,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control5() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 7 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 7 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.Href = "~/Styles/Site.css";
            
            #line default
            #line hidden
            
            #line 7 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 7 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        321,
                        66,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control6() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        448,
                        5,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ContentPlaceHolder @__BuildControlHeadContent() {
            global::System.Web.UI.WebControls.ContentPlaceHolder @__ctrl;
            
            #line 8 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl = new global::System.Web.UI.WebControls.ContentPlaceHolder();
            
            #line default
            #line hidden
            this.HeadContent = @__ctrl;
            
            #line 8 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.ID = "HeadContent";
            
            #line default
            #line hidden
            if ((this.ContentTemplates != null)) {
                this.@__Template_HeadContent = ((System.Web.UI.ITemplate)(this.ContentTemplates["HeadContent"]));
            }
            if ((this.@__Template_HeadContent != null)) {
                this.InstantiateInContentPlaceHolder(@__ctrl, this.@__Template_HeadContent);
            }
            else {
                global::System.Web.UI.LiteralControl @__ctrl1;
                
                #line 8 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
                @__ctrl1 = this.@__BuildControl__control6();
                
                #line default
                #line hidden
                System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
                
                #line 8 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
                @__parser.AddParsedSubObject(@__ctrl1);
                
                #line default
                #line hidden
            }
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        392,
                        86,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlHead @__BuildControl__control3() {
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl;
            
            #line 5 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlHead("head");
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl1;
            
            #line 5 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl1 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 5 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl2;
            
            #line 5 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl2 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 5 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ContentPlaceHolder @__ctrl3;
            
            #line 5 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl3 = this.@__BuildControlHeadContent();
            
            #line default
            #line hidden
            
            #line 5 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        275,
                        211,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control7() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n<body>\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        486,
                        12,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control9() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n    <div class=\"page\">\n        <div class=\"header\">\n            <div class=\"titl" +
                    "e\">\n                <h1>\n                    My ASP.NET Application\n            " +
                    "    </h1>\n            </div>\n            <div class=\"loginDisplay\">\n            " +
                    "    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        519,
                        245,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control11() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n                        [ ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        877,
                        27,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control13() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("Log In");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        971,
                        6,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlAnchor @__BuildControl__control12() {
            global::System.Web.UI.HtmlControls.HtmlAnchor @__ctrl;
            
            #line 23 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlAnchor();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            
            #line 23 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.HRef = "~/Account/Login.aspx";
            
            #line default
            #line hidden
            
            #line 23 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.ID = "HeadLoginStatus";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 23 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl1 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 23 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        904,
                        77,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control14() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(" ]\n                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        981,
                        23,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control10(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 21 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl1 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 21 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlAnchor @__ctrl2;
            
            #line 21 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl2 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 21 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 21 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl3 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            
            #line 21 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control16() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n                        Welcome <span class=\"bold\">");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1063,
                        52,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.LoginName @__BuildControl__control17() {
            global::System.Web.UI.WebControls.LoginName @__ctrl;
            
            #line 26 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl = new global::System.Web.UI.WebControls.LoginName();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 26 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.ID = "HeadLoginName";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1115,
                        51,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control18() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("</span>!\n                        [ ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1166,
                        35,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.LoginStatus @__BuildControl__control19() {
            global::System.Web.UI.WebControls.LoginStatus @__ctrl;
            
            #line 27 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl = new global::System.Web.UI.WebControls.LoginStatus();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 27 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.ID = "HeadLoginStatus";
            
            #line default
            #line hidden
            
            #line 27 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.LogoutAction = global::System.Web.UI.WebControls.LogoutAction.Redirect;
            
            #line default
            #line hidden
            
            #line 27 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.LogoutText = "Log Out";
            
            #line default
            #line hidden
            
            #line 27 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.LogoutPageUrl = "~/";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1201,
                        118,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control20() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(" ]\n                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1319,
                        23,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control15(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 21 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl1 = this.@__BuildControl__control16();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 21 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.LoginName @__ctrl2;
            
            #line 21 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl2 = this.@__BuildControl__control17();
            
            #line default
            #line hidden
            
            #line 21 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 21 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl3 = this.@__BuildControl__control18();
            
            #line default
            #line hidden
            
            #line 21 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.LoginStatus @__ctrl4;
            
            #line 21 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl4 = this.@__BuildControl__control19();
            
            #line default
            #line hidden
            
            #line 21 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 21 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl5 = this.@__BuildControl__control20();
            
            #line default
            #line hidden
            
            #line 21 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.LoginView @__BuildControlHeadLoginView() {
            global::System.Web.UI.WebControls.LoginView @__ctrl;
            
            #line 21 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl = new global::System.Web.UI.WebControls.LoginView();
            
            #line default
            #line hidden
            this.HeadLoginView = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 21 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.AnonymousTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control10));
            
            #line default
            #line hidden
            
            #line 21 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.LoggedInTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control15));
            
            #line default
            #line hidden
            
            #line 21 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.ID = "HeadLoginView";
            
            #line default
            #line hidden
            
            #line 21 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.EnableViewState = false;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        764,
                        630,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control21() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n            </div>\n            <div class=\"clear hideSkiplink\">\n                " +
                    "");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1394,
                        81,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.MenuItem @__BuildControl__control23() {
            global::System.Web.UI.WebControls.MenuItem @__ctrl;
            
            #line 34 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl = new global::System.Web.UI.WebControls.MenuItem();
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.NavigateUrl = "ProductHome.aspx";
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.Text = "Home";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.MenuItem @__BuildControl__control26() {
            global::System.Web.UI.WebControls.MenuItem @__ctrl;
            
            #line 38 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl = new global::System.Web.UI.WebControls.MenuItem();
            
            #line default
            #line hidden
            
            #line 38 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.NavigateUrl = "wheelall.aspx";
            
            #line default
            #line hidden
            
            #line 38 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.Text = "View All";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control25(System.Web.UI.WebControls.MenuItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.MenuItem @__ctrl1;
            
            #line 37 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl1 = this.@__BuildControl__control26();
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.MenuItem @__BuildControl__control24() {
            global::System.Web.UI.WebControls.MenuItem @__ctrl;
            
            #line 37 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl = new global::System.Web.UI.WebControls.MenuItem();
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.NavigateUrl = "Wheels.aspx";
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.Text = "Wheels";
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            this.@__BuildControl__control25(@__ctrl.ChildItems);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.MenuItem @__BuildControl__control27() {
            global::System.Web.UI.WebControls.MenuItem @__ctrl;
            
            #line 40 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl = new global::System.Web.UI.WebControls.MenuItem();
            
            #line default
            #line hidden
            
            #line 40 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.NavigateUrl = "Tires.aspx";
            
            #line default
            #line hidden
            
            #line 40 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.Text = "Tires";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.MenuItem @__BuildControl__control28() {
            global::System.Web.UI.WebControls.MenuItem @__ctrl;
            
            #line 41 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl = new global::System.Web.UI.WebControls.MenuItem();
            
            #line default
            #line hidden
            
            #line 41 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.NavigateUrl = "Accessories.aspx";
            
            #line default
            #line hidden
            
            #line 41 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.Text = "Accessories";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control22(System.Web.UI.WebControls.MenuItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.MenuItem @__ctrl1;
            
            #line 32 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl1 = this.@__BuildControl__control23();
            
            #line default
            #line hidden
            
            #line 32 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.MenuItem @__ctrl2;
            
            #line 32 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl2 = this.@__BuildControl__control24();
            
            #line default
            #line hidden
            
            #line 32 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.MenuItem @__ctrl3;
            
            #line 32 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl3 = this.@__BuildControl__control27();
            
            #line default
            #line hidden
            
            #line 32 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.MenuItem @__ctrl4;
            
            #line 32 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl4 = this.@__BuildControl__control28();
            
            #line default
            #line hidden
            
            #line 32 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.Add(@__ctrl4);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Menu @__BuildControlNavigationMenu() {
            global::System.Web.UI.WebControls.Menu @__ctrl;
            
            #line 32 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl = new global::System.Web.UI.WebControls.Menu();
            
            #line default
            #line hidden
            this.NavigationMenu = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            
            #line 32 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.ID = "NavigationMenu";
            
            #line default
            #line hidden
            
            #line 32 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.CssClass = "menu";
            
            #line default
            #line hidden
            
            #line 32 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.EnableViewState = false;
            
            #line default
            #line hidden
            
            #line 32 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.IncludeStyleBlock = false;
            
            #line default
            #line hidden
            
            #line 32 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.Orientation = global::System.Web.UI.WebControls.Orientation.Horizontal;
            
            #line default
            #line hidden
            
            #line 32 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            this.@__BuildControl__control22(@__ctrl.Items);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1475,
                        806,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control29() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n            </div>\n        </div>\n        <div class=\"main\">\n            ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2281,
                        74,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ContentPlaceHolder @__BuildControlMainContent() {
            global::System.Web.UI.WebControls.ContentPlaceHolder @__ctrl;
            
            #line 48 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl = new global::System.Web.UI.WebControls.ContentPlaceHolder();
            
            #line default
            #line hidden
            this.MainContent = @__ctrl;
            
            #line 48 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl.ID = "MainContent";
            
            #line default
            #line hidden
            if ((this.ContentTemplates != null)) {
                this.@__Template_MainContent = ((System.Web.UI.ITemplate)(this.ContentTemplates["MainContent"]));
            }
            if ((this.@__Template_MainContent != null)) {
                this.InstantiateInContentPlaceHolder(@__ctrl, this.@__Template_MainContent);
            }
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2355,
                        57,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control30() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n        </div>\n        <div class=\"clear\">\n        </div>\n    </div>\n    <div cl" +
                    "ass=\"footer\">\n        \n    </div>\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2412,
                        119,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControl__control8() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 12 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 12 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl1 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 12 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.LoginView @__ctrl2;
            
            #line 12 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl2 = this.@__BuildControlHeadLoginView();
            
            #line default
            #line hidden
            
            #line 12 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 12 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl3 = this.@__BuildControl__control21();
            
            #line default
            #line hidden
            
            #line 12 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Menu @__ctrl4;
            
            #line 12 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl4 = this.@__BuildControlNavigationMenu();
            
            #line default
            #line hidden
            
            #line 12 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 12 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl5 = this.@__BuildControl__control29();
            
            #line default
            #line hidden
            
            #line 12 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ContentPlaceHolder @__ctrl6;
            
            #line 12 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl6 = this.@__BuildControlMainContent();
            
            #line default
            #line hidden
            
            #line 12 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl7;
            
            #line 12 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl7 = this.@__BuildControl__control30();
            
            #line default
            #line hidden
            
            #line 12 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        498,
                        2040,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control31() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n</body>\n</html>\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2538,
                        17,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(products_productsite_master @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl2;
            
            #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl2 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl3 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl4;
            
            #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl4 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__ctrl5 = this.@__BuildControl__control31();
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Products\ProductSite.master.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
        }
        
        #line default
        #line hidden
    }
}
