#pragma checksum "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "5F92CF750A5098CCA87AECBC81BB7D8274CB7FDC"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Account_ChangePassword : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
    protected global::System.Web.UI.WebControls.ChangePassword ChangeUserPassword;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected ASP.global_asax ApplicationInstance {
        get {
            return ((ASP.global_asax)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 4 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 387 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 393 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 400 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 4 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 388 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 392 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 398 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 391 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 395 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 4 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 396 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 4 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 390 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 399 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 386 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 4 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 394 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 389 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 405 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 404 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class account_changepassword_aspx : global::Account_ChangePassword, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.account_changepassword_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static System.Reflection.MethodInfo @__PageInspector_BeginRenderTracingMethod = global::ASP.account_changepassword_aspx.@__PageInspector_LoadHelper("BeginRenderTracing");
        
        private static System.Reflection.MethodInfo @__PageInspector_EndRenderTracingMethod = global::ASP.account_changepassword_aspx.@__PageInspector_LoadHelper("EndRenderTracing");
        
        private static bool @__initialized;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public account_changepassword_aspx() {
            string[] dependencies;
            
            #line 912304 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/Account/ChangePassword.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.account_changepassword_aspx.@__initialized == false)) {
                dependencies = new string[4];
                dependencies[0] = "~/Account/ChangePassword.aspx";
                dependencies[1] = "~/Site.master";
                dependencies[2] = "~/Site.master.cs";
                dependencies[3] = "~/Account/ChangePassword.aspx.cs";
                global::ASP.account_changepassword_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.account_changepassword_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        259,
                        1,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.VisualStudio.Web.PageInspector.Runtime.WebForms.TraceHelpers, Microsoft" +
                    ".VisualStudio.Web.PageInspector.Runtime, Version=1.3.0.0, Culture=neutral, Publi" +
                    "cKeyToken=b03f5f7f11d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.account_changepassword_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.account_changepassword_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        private void @__PageInspector_BeginRenderTracing(object[] parameters) {
            if ((global::ASP.account_changepassword_aspx.@__PageInspector_BeginRenderTracingMethod != null)) {
                global::ASP.account_changepassword_aspx.@__PageInspector_BeginRenderTracingMethod.Invoke(null, parameters);
            }
        }
        
        private void @__PageInspector_EndRenderTracing(object[] parameters) {
            if ((global::ASP.account_changepassword_aspx.@__PageInspector_EndRenderTracingMethod != null)) {
                global::ASP.account_changepassword_aspx.@__PageInspector_EndRenderTracingMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlHeaderContent(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 4 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 4 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control4() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n            <span class=\"failureNotification\">\n                ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        834,
                        64,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Literal @__BuildControl__control5() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            
            #line 20 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            
            #line 20 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ID = "FailureText";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        898,
                        59,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control6() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n            </span>\n            ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        957,
                        33,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ValidationSummary @__BuildControl__control7() {
            global::System.Web.UI.WebControls.ValidationSummary @__ctrl;
            
            #line 22 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ValidationSummary();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 22 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ID = "ChangeUserPasswordValidationSummary";
            
            #line default
            #line hidden
            
            #line 22 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.CssClass = "failureNotification";
            
            #line default
            #line hidden
            
            #line 22 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ValidationGroup = "ChangeUserPasswordValidationGroup";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        990,
                        181,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control8() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n            <div class=\"accountInfo\">\n                <fieldset class=\"changePas" +
                    "sword\">\n                    <legend>Account Information</legend>\n               " +
                    "     <p>\n                        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1171,
                        194,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control10() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("Old Password:");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1455,
                        13,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControl__control9() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 28 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 28 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ID = "CurrentPasswordLabel";
            
            #line default
            #line hidden
            
            #line 28 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.AssociatedControlID = "CurrentPassword";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 28 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl1 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 28 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1365,
                        115,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control11() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n                        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1480,
                        25,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControl__control12() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 29 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 29 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ID = "CurrentPassword";
            
            #line default
            #line hidden
            
            #line 29 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.CssClass = "passwordEntry";
            
            #line default
            #line hidden
            
            #line 29 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Password;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1505,
                        108,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control13() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n                        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1613,
                        25,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control15() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("*");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1962,
                        1,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControl__control14() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 30 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 30 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ID = "CurrentPasswordRequired";
            
            #line default
            #line hidden
            
            #line 30 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ControlToValidate = "CurrentPassword";
            
            #line default
            #line hidden
            
            #line 30 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.CssClass = "failureNotification";
            
            #line default
            #line hidden
            
            #line 30 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ErrorMessage = "Password is required.";
            
            #line default
            #line hidden
            
            #line 30 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ToolTip = "Old Password is required.";
            
            #line default
            #line hidden
            
            #line 30 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ValidationGroup = "ChangeUserPasswordValidationGroup";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 30 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl1 = this.@__BuildControl__control15();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 30 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1638,
                        354,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control16() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n                    </p>\n                    <p>\n                        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1992,
                        74,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control18() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("New Password:");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2148,
                        13,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControl__control17() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 35 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 35 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ID = "NewPasswordLabel";
            
            #line default
            #line hidden
            
            #line 35 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.AssociatedControlID = "NewPassword";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 35 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl1 = this.@__BuildControl__control18();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 35 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2066,
                        107,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control19() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n                        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2173,
                        25,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControl__control20() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 36 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 36 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ID = "NewPassword";
            
            #line default
            #line hidden
            
            #line 36 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.CssClass = "passwordEntry";
            
            #line default
            #line hidden
            
            #line 36 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Password;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2198,
                        104,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control21() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n                        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2302,
                        25,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control23() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("*");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2647,
                        1,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControl__control22() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 37 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 37 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ID = "NewPasswordRequired";
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ControlToValidate = "NewPassword";
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.CssClass = "failureNotification";
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ErrorMessage = "New Password is required.";
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ToolTip = "New Password is required.";
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ValidationGroup = "ChangeUserPasswordValidationGroup";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 37 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl1 = this.@__BuildControl__control23();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 37 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2327,
                        350,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control24() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n                    </p>\n                    <p>\n                        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2677,
                        74,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control26() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("Confirm New Password:");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2847,
                        21,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControl__control25() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 42 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 42 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ID = "ConfirmNewPasswordLabel";
            
            #line default
            #line hidden
            
            #line 42 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.AssociatedControlID = "ConfirmNewPassword";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 42 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl1 = this.@__BuildControl__control26();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 42 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2751,
                        129,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control27() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n                        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2880,
                        25,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControl__control28() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 43 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 43 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ID = "ConfirmNewPassword";
            
            #line default
            #line hidden
            
            #line 43 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.CssClass = "passwordEntry";
            
            #line default
            #line hidden
            
            #line 43 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Password;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2905,
                        111,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control29() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n                        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3016,
                        25,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control31() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("*");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3408,
                        1,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControl__control30() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 44 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 44 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ID = "ConfirmNewPasswordRequired";
            
            #line default
            #line hidden
            
            #line 44 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ControlToValidate = "ConfirmNewPassword";
            
            #line default
            #line hidden
            
            #line 44 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.CssClass = "failureNotification";
            
            #line default
            #line hidden
            
            #line 44 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 44 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ErrorMessage = "Confirm New Password is required.";
            
            #line default
            #line hidden
            
            #line 44 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ToolTip = "Confirm New Password is required.";
            
            #line default
            #line hidden
            
            #line 44 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ValidationGroup = "ChangeUserPasswordValidationGroup";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 44 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl1 = this.@__BuildControl__control31();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 44 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3041,
                        397,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control32() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n                        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3438,
                        25,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control34() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("*");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3829,
                        1,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CompareValidator @__BuildControl__control33() {
            global::System.Web.UI.WebControls.CompareValidator @__ctrl;
            
            #line 47 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CompareValidator();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 47 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ID = "NewPasswordCompare";
            
            #line default
            #line hidden
            
            #line 47 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ControlToCompare = "NewPassword";
            
            #line default
            #line hidden
            
            #line 47 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ControlToValidate = "ConfirmNewPassword";
            
            #line default
            #line hidden
            
            #line 47 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.CssClass = "failureNotification";
            
            #line default
            #line hidden
            
            #line 47 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 47 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ErrorMessage = "The Confirm New Password must match the New Password entry.";
            
            #line default
            #line hidden
            
            #line 47 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ValidationGroup = "ChangeUserPasswordValidationGroup";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 47 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl1 = this.@__BuildControl__control34();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 47 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3463,
                        390,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control35() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n                    </p>\n                </fieldset>\n                <p class=\"s" +
                    "ubmitButton\">\n                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3853,
                        115,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControl__control36() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 53 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 53 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ID = "CancelPushButton";
            
            #line default
            #line hidden
            
            #line 53 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.CausesValidation = false;
            
            #line default
            #line hidden
            
            #line 53 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.CommandName = "Cancel";
            
            #line default
            #line hidden
            
            #line 53 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.Text = "Cancel";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3968,
                        110,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control37() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4078,
                        21,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControl__control38() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 54 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 54 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ID = "ChangePasswordPushButton";
            
            #line default
            #line hidden
            
            #line 54 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.CommandName = "ChangePassword";
            
            #line default
            #line hidden
            
            #line 54 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.Text = "Change Password";
            
            #line default
            #line hidden
            
            #line 54 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ValidationGroup = "ChangeUserPasswordValidationGroup";
            
            #line default
            #line hidden
            
            #line 54 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.Click += new System.EventHandler(this.ChangePasswordPushButton_Click);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4099,
                        229,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control39() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n                </p>\n            </div>\n        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4328,
                        49,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control3(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl1 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Literal @__ctrl2;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl2 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl3 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ValidationSummary @__ctrl4;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl4 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl5 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl6;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl6 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl7;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl7 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl8;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl8 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl9;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl9 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl10;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl10 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl11;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl11 = this.@__BuildControl__control16();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl12;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl12 = this.@__BuildControl__control17();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl13;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl13 = this.@__BuildControl__control19();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl13);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl14;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl14 = this.@__BuildControl__control20();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl14);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl15;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl15 = this.@__BuildControl__control21();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl15);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl16;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl16 = this.@__BuildControl__control22();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl16);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl17;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl17 = this.@__BuildControl__control24();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl17);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl18;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl18 = this.@__BuildControl__control25();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl18);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl19;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl19 = this.@__BuildControl__control27();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl19);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl20;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl20 = this.@__BuildControl__control28();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl20);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl21;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl21 = this.@__BuildControl__control29();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl21);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl22;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl22 = this.@__BuildControl__control30();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl22);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl23;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl23 = this.@__BuildControl__control32();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl23);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CompareValidator @__ctrl24;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl24 = this.@__BuildControl__control33();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl24);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl25;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl25 = this.@__BuildControl__control35();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl25);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl26;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl26 = this.@__BuildControl__control36();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl26);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl27;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl27 = this.@__BuildControl__control37();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl27);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl28;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl28 = this.@__BuildControl__control38();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl28);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl29;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl29 = this.@__BuildControl__control39();
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl29);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ChangePassword @__BuildControlChangeUserPassword() {
            global::System.Web.UI.WebControls.ChangePassword @__ctrl;
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ChangePassword();
            
            #line default
            #line hidden
            this.ChangeUserPassword = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ChangePasswordTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control3));
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.ID = "ChangeUserPassword";
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.CancelDestinationPageUrl = "~/";
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.EnableViewState = false;
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.RenderOuterTable = false;
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.SuccessPageUrl = "ChangePasswordSuccess.aspx";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        609,
                        3819,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlBodyContent(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.WebControls.ChangePassword @__ctrl1;
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl1 = this.@__BuildControlChangeUserPassword();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderBodyContent));
        }
        
        private void @__RenderBodyContent(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/C:/Users/Neo/Documents/GitHub/OBG/OBG_System/OBG_System/Account/ChangePassword.a" +
                            "spx",
                        355,
                        175,
                        true});
            @__w.Write("\n    <h2>\n        Change Password\n    </h2>\n    <p>\n        Use the form below to" +
                    " change your password.\n    </p>\n    <p>\n        New passwords are required to be" +
                    " a minimum of ");
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/C:/Users/Neo/Documents/GitHub/OBG/OBG_System/OBG_System/Account/ChangePassword.a" +
                            "spx",
                        530,
                        43,
                        false});
            
            #line 14 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
                                              @__w.Write( Membership.MinRequiredPasswordLength );

            
            #line default
            #line hidden
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/C:/Users/Neo/Documents/GitHub/OBG/OBG_System/OBG_System/Account/ChangePassword.a" +
                            "spx",
                        573,
                        36,
                        true});
            @__w.Write(" characters in length.\n    </p>\n    ");
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            parameterContainer.Controls[0].RenderControl(@__w);
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/C:/Users/Neo/Documents/GitHub/OBG/OBG_System/OBG_System/Account/ChangePassword.a" +
                            "spx",
                        4428,
                        1,
                        true});
            @__w.Write("\n");
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(account_changepassword_aspx @__ctrl) {
            
            #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.Title = "Change Password";
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__ctrl.MasterPageFile = "~/Site.master";
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 4 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            this.AddContentTemplate("HeadContent", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlHeaderContent)));
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            this.AddContentTemplate("MainContent", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlBodyContent)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "C:\Users\Neo\Documents\GitHub\OBG\OBG_System\OBG_System\Account\ChangePassword.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.account_changepassword_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 1707635701;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
